[[user]]
id = "test"
groups = ["test_group"]
files = [
	"test.txt",
	"foo/sub.png",
	"empty",
]

[[user]]
id = "test2"
groups = ["test"]
files = [
	"range/a[1..3]/b[1..3].txt"
]

[[share]]
from = "test"
to = "test2"
file = "foo/sub.png"

[[share]]
from = "test"
to = "test2"
file = "test.txt"
target = "target_folder/shared.txt"
permissions = 15
